DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 128
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.002
  MAX_EPOCH: 50
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 5

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

DATASET:
  NAME: OfficeHomeDG
  ROOT: data
  SOURCE_DOMAINS: ["art", "product", "real_world"]
  TARGET_DOMAINS: ["clipart"]

TRAINER:
  NAME: CSDG
  CSDG:
    CONTENT:
      CTX_INIT: True
    STYLE:
      USE_DOMAIN_ID: True
    GATE:
      INIT_BIAS: 0.0
      DETACH_STYLE_GRAD: False
      BIAS_TARGET: null
      BIAS_TARGET_EPOCH: null
    LOSS:
      STYLE_DECORR_WEIGHT: 0.1
      GATE_ENT_WEIGHT: 0.05
      STYLE_CE_WEIGHT: 0.05
      GATE_ENT_WEIGHT_TARGET: null
      GATE_ENT_WEIGHT_TARGET_EPOCH: null

OUTPUT_DIR: outputs/csdg_office_home_clipart_standard
